export enum BitcoinistCategory {
  BITCOIN = 'BITCOIN',
  BITCOIN_PRICE = 'BITCOIN_PRICE',
  BITCOIN_BUSINESSES = 'BITCOIN_BUSINESSES',
  BITCOIN_ACCEPTANCE = 'BITCOIN_ACCEPTANCE',
  BITCOIN_TECHNOLOGY = 'BITCOIN_TECHNOLOGY',
  BITCOIN_INVESTMENT = 'BITCOIN_INVESTMENT',
  BITCOIN_REGULATION = 'BITCOIN_REGULATION',
  BITCOIN_REVIEWS = 'BITCOIN_REVIEWS',
  ALTCOINS = 'ALTCOINS',
  ALTCOINS_PRICE = 'ALTCOINS_PRICE',
  ETHEREUM = 'ETHEREUM',
  RIPPLE = 'RIPPLE',
  LITECOIN = 'LITECOIN',
  EOS = 'EOS',
  NAGA = 'NAGA',
  BLOCKCHAIN = 'BLOCKCHAIN',
  BITCOIN_SECURITY = 'BITCOIN_SECURITY',
  FIN_TECH = 'FIN_TECH',
  INDUSTRY = 'INDUSTRY',
}

export enum CoinDeskCategory {
  MARKETS = 'MARKETS',
  BUSINESS = 'BUSINESS',
  TECH = 'TECH',
  POLICY = 'POLICY',
}

export enum CointelegraphCategory {
  BITCOIN = 'BITCOIN',
  MARKETS = 'MARKETS',
  ETHEREUM = 'ETHEREUM',
  ALTCOIN = 'ALTCOIN',
  BLOCKCHAIN = 'BLOCKCHAIN',
  REGULATION = 'REGULATION',
  OPINION = 'OPINION',
  INTERVIEW = 'INTERVIEW',
  INVESTIGATION = 'INVESTIGATION',
  FEATURES = 'FEATURES',
  HOW_TO = 'HOW-TO',
}

export enum CryptoDailyCategory {
  BITCOIN = 'BITCOIN',
  ETHEREUM = 'ETHEREUM',
  DEFI = 'DEFI',
  ALTCOINS = 'ALTCOINS',
  TRADING = 'TRADING',
  TECHNOLOGY = 'TECHNOLOGY',
  BUSINESS = 'BUSINESS',
  OPINION = 'OPINION',
  WEB3 = 'WEB3',
  SECURITY = 'SECURITY',
  PR = 'PR',
  REGULATION = 'REGULATION',
  GAMBLING = 'GAMBLING',
  WALLETS = 'WALLETS',
  CRYPTO_EXCHANGE = 'CRYPTO_EXCHANGE',
  LENDING = 'LENDING',
  MINING = 'MINING',
}

export enum CryptoNewsCategory {
  BITCOIN = 'BITCOIN',
  ETHEREUM = 'ETHEREUM',
  BLOCKCHAIN = 'BLOCKCHAIN',
  DEFI = 'DEFI',
  ALTCOIN = 'ALTCOIN',
  REGULATION = 'REGULATION',
  SOLANA = 'SOLANA',
  SHIBA = 'SHIBA',
  FEATURE = 'FEATURE',
  OPINION = 'OPINION',
  FOLLOW_UP = 'FOLLOW_UP',
  MARKET = 'MARKET',
  SPONSORED = 'SPONSORED',
  XRP = 'XRP',
  LEARN = 'LEARN',
  INTERVIEW = 'INTERVIEW',
  PREDICTION = 'PREDICTION',
}

export enum DecryptCategory {
  NEWS = 'NEWS',
  BUSINESS = 'BUSINESS',
  ARTIFICIAL_INTELLIGENCE = 'ARTIFICIAL_INTELLIGENCE',
  TECHNOLOGY = 'TECHNOLOGY',
  NFT = 'NFT',
  CRYPTOCURRENCIES = 'CRYPTOCURRENCIES',
  DEFI = 'DEFI',
  GAMING = 'GAMING',
  MARKETS = 'MARKETS',
  OPINION = 'OPINION',
}

export enum DecryptSort {
  PUBLISHED = 'PUBLISHED',
  SCORE = 'SCORE',
}
